# GitHub Actions CI pipeline for Python application
# Place this file in the .github/workflows directory of your repository
name: Python CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Static Code Analysis
      run: |
        pip install pylint
        pylint **/*.py

    - name: Run Unit Tests
      run: |
        pip install pytest
        pytest tests/
